source 'http://rubygems.org'

gem 'rails', '3.0.3'
gem 'json'
gem 'god'
gem 'unicorn'
gem 'mysql'
gem 'sqlite3-ruby', :require => 'sqlite3'
gem "resque", :require => "resque/server"
gem 'acts-as-taggable-on'
gem 'ancestry'
gem 'feed-normalizer'
gem 'nokogiri'
gem "devise", '1.2.rc'
gem "oa-oauth", :require => "omniauth/oauth"
gem 'rmagick',    :require => 'RMagick'         # only if used
gem 'rack-cache', :require => 'rack/cache'      # only if used
gem 'dragonfly'
gem 'activequeue'
gem 'compass'
gem 'typhoeus'
gem 'capybara'
gem 'database_cleaner'
gem 'cucumber-rails'
gem 'cucumber'
gem 'rspec-rails'
gem 'autotest'
gem 'machinist'
gem 'spork'
gem 'launchy'
gem 'pickle'
gem 'googlecharts'
gem 'metric_fu'
gem 'ruby-prof'
gem 'rspec', :group => :test
gem 'hirb'